// app/components/studio/StudioActivityLog.tsx
"use client";

type EventRow = {
  id: string;
  event_type: string;
  details?: Record<string, any>;
  created_at: string;
};

function label(row: EventRow) {
  const details = row.details || {};

  switch (row.event_type) {
    case "claim_requested":
      return "Collection claim requested";
    case "claim_status_changed":
      return (
        "Claim status: " +
        String(details.from || "unknown").toUpperCase() +
        " → " +
        String(details.to || "unknown").toUpperCase()
      );
    case "collection_status_changed":
      return (
        "Project status: " +
        String(details.from || "unknown").toUpperCase() +
        " → " +
        String(details.to || "unknown").toUpperCase()
      );
    case "background_status_changed":
      return (
        "Background " +
        String(details.name || "package") +
        ": " +
        String(details.from || "unknown").toUpperCase() +
        " → " +
        String(details.to || "unknown").toUpperCase()
      );
    default:
      return row.event_type.replace(/_/g, " ");
  }
}

function formatDate(value: string) {
  try {
    return new Intl.DateTimeFormat(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    }).format(new Date(value));
  } catch {
    return value;
  }
}

export default function StudioActivityLog({
  events,
}: {
  events: EventRow[];
}) {
  return (
    <section style={panel}>
      <div style={eyebrow}>LOCKSCREENED ACTIVITY + SECURITY LOG</div>
      <h2 style={heading}>Project history</h2>
      <p style={copy}>
        These entries are generated by database state changes, not by browser
        success messages. They provide a durable record of important claim and
        publishing events for this project.
      </p>

      {!events?.length ? (
        <div style={empty}>No security-relevant project events yet.</div>
      ) : (
        <div style={{ marginTop: 12, display: "grid", gap: 7 }}>
          {events.map((event) => (
            <div key={event.id} style={row}>
              <span style={dot} aria-hidden="true" />
              <div style={{ minWidth: 0, flex: 1 }}>
                <strong
                  style={{
                    display: "block",
                    fontSize: 9,
                    textTransform: "capitalize",
                  }}
                >
                  {label(event)}
                </strong>
                <span
                  style={{
                    display: "block",
                    marginTop: 2,
                    color: "rgba(255,255,255,.38)",
                    fontSize: 8,
                  }}
                >
                  {formatDate(event.created_at)}
                </span>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

const panel = {
  borderRadius: 22,
  padding: 20,
  border: "1px solid rgba(255,99,194,.12)",
  background:
    "linear-gradient(135deg, rgba(14,10,28,.74), rgba(9,8,18,.64))",
} as const;

const eyebrow = {
  color: "#ff8dce",
  fontSize: 9,
  fontWeight: 900,
  letterSpacing: ".17em",
} as const;

const heading = {
  margin: "6px 0 5px",
  fontSize: 19,
} as const;

const copy = {
  margin: 0,
  color: "rgba(255,255,255,.54)",
  fontSize: 10,
  lineHeight: 1.55,
} as const;

const row = {
  borderRadius: 11,
  padding: "8px 9px",
  border: "1px solid rgba(255,255,255,.06)",
  background: "rgba(255,255,255,.02)",
  display: "flex",
  gap: 8,
  alignItems: "center",
} as const;

const dot = {
  width: 7,
  height: 7,
  borderRadius: 999,
  background: "#a9ffd2",
  boxShadow: "0 0 10px rgba(169,255,210,.3)",
  flex: "0 0 auto",
} as const;

const empty = {
  marginTop: 12,
  borderRadius: 11,
  padding: 10,
  border: "1px solid rgba(255,255,255,.06)",
  color: "rgba(255,255,255,.4)",
  fontSize: 9,
} as const;
